export const moduleGrades = [
  {
    module: "CI411 - Introduction to Games Programming",
    assignmentOne: "Portfolio",
    assignmentTwo: "Game",
    gradeOne: 68,
    gradeTwo: 58,
    finalGrade: 63,
  },
  {
    module: "CI410  - Introduction to Game Design and Development",
    assignmentOne: "Game Design",
    assignmentTwo: "Game Prototype",
    gradeOne: 71,
    gradeTwo: 42,
    finalGrade: 57,
  },
  {
    module: "CI435 - Introduction to Web Development",
    assignmentOne: "Coursework",
    assignmentTwo: "Examination",
    gradeOne: 63,
    gradeTwo: 81,
    finalGrade: 72,
  },
  {
    module: "CI474 - Introduction to 3D Modelling and Animation",
    assignmentOne: "Portfolio Task 1",
    assignmentTwo: "Portfolio Task 2",
    gradeOne: 71,
    gradeTwo: 68,
    finalGrade: 69,
  },
  {
    module: "CI465 - Working in the Digital and Games Industries",
    assignmentOne: "Group Project",
    assignmentTwo: "Individual Project",
    gradeOne: 67,
    gradeTwo: 58,
    finalGrade: 63,
  },
  {
    module: "CI413 - Game Level and Asset Design",
    assignmentOne: "Level design with original assets",
    assignmentTwo: "Group Report",
    gradeOne: 55,
    gradeTwo: 85,
    finalGrade: 67,
  },
  {
    module: "CI541 - Game Development Frameworks",
    assignmentOne: "3D game project",
    gradeOne: 68,
    finalGrade: 68,
  },
  {
    module: "CI587 - Web based game development",
    assignmentOne: "Game Development Project",
    gradeOne: 78,
    finalGrade: 78,
  },
  {
    module: "CI536 - Integrated Group Project",
    assignmentOne: "Group Project",
    gradeOne: 77,
    finalGrade: 77,
  },
  {
    module: "CI520 - Narrative Game Design",
    assignmentOne: "Game Concept and Prototype",
    gradeOne: 67,
    finalGrade: 67,
  },
  {
    module: "CI517 - Game Engine Fundamentals",
    assignmentOne: "Game Engine Components",
    gradeOne: 65,
    finalGrade: 65,
  },
  {
    module: "CI516 - Artificial Intelligence for Games",
    assignmentOne: "Game AI Prototype",
    assignmentTwo: "Game AI Report",
    gradeOne: 38,
    gradeTwo: 48,
    finalGrade: 42,
  },
];
