export const modules = [
  {
    title: "CI411 - Introduction to Games Programming",
    year: "2022 - 2023",
    semester: "3",
    details: [],
    content: [
      "Problem Solving",
      "Data types and expressions",
      "Core features of C++",
      "Object-Oriented Programming",
      "Game Development",
      "Programming Development Tools and Techniques",
    ],
    githubrepo:"https://github.com/KennedySovine/CI411_Games_Programming ",
  },
  {
    title: "CI410  - Introduction to Game Design and Development",
    year: "2022 - 2023",
    semester: "3",
    details: [],
    content: [
      "History of Computer Games",
      "Video Games and Seizure Safety",
      "Game Accessibility Guidelines",
      "Key elements of game design",
      "Effectively pitching and communicating a design",
      "Creating and editing game assets",
      "Introduction to game frameworks and rapid prototyping",
      "Coordinate systems and the camera",
      "Simple games architecture",
      "Demonstrate the use of the game engine's physics system",
    ],
    githubrepo: "https://github.com/KennedySovine/CI410-Introduction-to-Game-Design-and-Development",
  },
  {
    title: "CI435 - Introduction to Web Development",
    year: "2022 - 2023",
    semester: "3",
    details: [],
    content: [
      "Introduction to web standards",
      "Current web standards and the organisations responsible",
      "Browsers and user agents",
      "Accessibility",
      "Design ethics",
      "Economic context of the development, use, and maintenance of web sites",
      "HTML5/CSS web development",
      "HTML markup – syntax and semantics to structure content",
      "Creating content – text, image, media, forms",
      "Website navigation – lists and anchors",
      "Cascading stylesheets (CSS) – presentation, media queries",
      "Fluid and responsive web page layouts",
      "Testing and validation",
      "Website production",
      "Responsive web design workflow",
      "Web development tools",
      "File organisation and management",
      "Client-side scripting",
      "Introduction to JavaScript",
      "Events and Event Listeners",
      "Document Object Model (DOM) - Accessing and manipulating elements - Dynamically generating elements - Dynamically styling elements",
      "Accessing and validating form values"
    ],
    githubrepo: "https://github.com/KennedySovine/CI435-Introduction-to-Web-Development",
  },
  {
    title: "CI474 - Introduction to 3D Modelling and Animation",
    year: "2022 - 2023",
    semester: "3",
    details: [],
    content: [
      "Production planning, visual research, concept art creation and use",
      "Modelling objects and backgrounds using primitives",
      "Building basic environments: objects, lights and cameras",
      "Object hierarchies and their uses",
      "Creating and modifying meshes and splines",
      "Creating and modifying revolved and lofted objects",
      "Shader materials and texture maps",
      "Basic keyframe animation",
      "3d camera animation",
      "Rendering",
      "Legal, ethical and professional issues within animation",
      "Production planning and time management"
    ],
    githubrepo: "https://github.com/KennedySovine/CI474_Introduction_3D_Modeling_and_Animation",
  },
  {
    title:"CI465 - Working in the Digital and Games Industries",
    year: "2022 - 2023",
    semester: "1",
    details: [],
    content: [
      "National and global economy",
      "Culture, organisations and business models",
      "Working practices in digital enterprises",
      "Careers, employment roles and skills",
      "Legal and ethical issues",
      "Information Security",
      "Creating an online presence",
      "Digital portfolio of work",
      "Platforms for sharing code/design work – e.g., CodePen, Behance",
      "Social media and professional networks",
      "CV writing",
      "Communication using different media",
      "Planning and working in a group and as an individual",
      "Academic writing and referencing",
      "Finding and using information to investigate a topic"
    ],
  },
  {
    title: "CI413 - Game Level and Asset Design",
    year: "2022 - 2023",
    semester: "2",
    details: [],
    content: [
      "Design fundamentals",
      "Visual design",
      "Asset design tools and techniques",
      "Image editing",
      "Audio editing",
      "Defining game levels",
      "The level design and development process",
      "Conceptualising, planning, and designing Levels",
      "Creating level maps and flow diagrams",
      "Playtesting Levels",
      "Designing and creating environments for game levels",
      "Designing level encounters and puzzles"
    ],
    githubrepo: "https://github.com/KennedySovine/CI413-Game-Level-and-Asset-Design",
  },
  // ...LEVEL 5 & 6 MODULES (truncated for brevity, but would be included in full)...
];
